name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-licence-and-test:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install tox

      - name: Cache licence-check
        uses: actions/cache@v2
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          PATH: src

      - name: Build and test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          tox
        shell: bash
