name: Release and deploy to Pypi

on:
  workflow_dispatch:

jobs:
  release-checks:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic
    env:
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - name: Release checks and update version for release
        id: check
        run: |
          /scripts/release-checks.sh --python setup.py
          /scripts/finalize-version.sh --python setup.py
        shell: bash

      - name: Cache licence-check
        uses: actions/cache@v2
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}
          PATH: src

  deploy:
    runs-on: ubuntu-latest
    container: python:3.7
    needs: release-checks
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Install dependencies
        run: |
          pip install tox twine

      - uses: actions/checkout@v2

      - name: Checkout release branch
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git checkout release
        shell: bash

      - name: Build and publish
        id: build
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          tox
          twine upload dist/*
          version=$(grep version setup.py | cut -d= -f2 | tr -d '",')
          artifact="pp-translator-${version}-py3-none-any.whl"
          echo "::set-output name=version::$(echo $version)"
          echo "::set-output name=artifact::$(echo $artifact)"
          echo "::set-output name=artifact-path::$(echo dist/$artifact)"
        shell: bash
        continue-on-error: true

      - uses: actions/upload-artifact@master
        if: steps.build.outcome == 'success'
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: ${{ steps.build.outputs.artifact-path }}

      - name: Delete release branch if deploy failed and fail
        if: steps.build.outcome == 'failure'
        run: |
          git push origin -d release
          echo "There was an error in the python build and publish commands above."
          exit 1
        shell: bash

  create-release:
    needs: [deploy]
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Merge and Tag
        id: merge
        env:
          VERSION: ${{ needs.deploy.outputs.version }}
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git merge origin/release
          git push origin ${GITHUB_REF/refs\/heads\//}
          git tag "v$VERSION"
          git push --tags
          echo "::set-output name=tag::$(echo v$VERSION)"
        shell: bash

      - name: Fail
        if: steps.merge.outcome == 'failure'
        run: | 
          git push origin -d release
          echo "There was an error in merging the branch. release branch was deleted."
          exit 1
        shell: bash

      - name: Create Release
        if: steps.merge.outcome == 'success'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.merge.outputs.tag }}
          release_name: ${{ steps.merge.outputs.tag }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.deploy.outputs.artifact }}
          path: built-artifacts

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: built-artifacts/${{ needs.deploy.outputs.artifact }}
          asset_name: ${{ needs.deploy.outputs.artifact }}
          asset_content_type: application/octet-stream

  update-version:
    needs: create-release
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic
    env:
      ZEPBEN_PYPI_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      ZEPBEN_PYPI_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      ZEPBEN_PYPI_REPO: ${{ secrets.ZEPBEN_PYPI_REPO }}
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2

      - name: Update to next minor version
        run: |
          /scripts/update-version.sh --python --release setup.py changelog.md
        shell: bash
